version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container-name
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: stock_exchange
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"

  app:
    build:
      context: .  # Use the current directory as the build context
      dockerfile: Dockerfile
    container_name: nodejs-container-name
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: root
      DB_NAME: stock_exchange
